version: '3.1'
services:
  consul:
    container_name: consul
    image: 'consul:latest'
    expose:
      - '8300'
      - '8301'
      - '8500'
      - '8600'
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      lb7_network:
        ipv4_address: '${CONSUL_IP}'
networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
