version: '3.1'
services:
  consul:
    container_name: consul
    image: 'consul:latest'
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    command: consul agent -server -client=10.0.1.242 -bind=10.0.1.122 -bootstrap-expect=1 -data-dir=/consul/data
    volumes:
      - ./consul/data:/consul/data
      - ./consul/consul.json:/consul/config/local.json
    expose:
      - '8300'
      - '8301'
      - '8500'
      - '8600'
    network_mode: "host"
